inicio: servidorCompilacion clienteCompilacion ok

servidorCompilacion: servidor.c funciones.c
	gcc servidor.c funciones.c -o servidor

clienteCompilacion: cliente.c funciones.c
	gcc cliente.c funciones.c -o cliente

ok:
	@echo "Compilacion finalizada"